# Generated by Django 5.0.6 on 2024-06-23 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_headquarters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Especialidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Funtionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField(max_length=30)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del funcionario')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellido del funcionario')),
                ('birthday', models.DateField(verbose_name='Edad')),
                ('telephone', models.CharField(max_length=10, verbose_name='Numero de celular')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo electronico')),
                ('active', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
                ('Headquarters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.headquarters')),
                ('speciality', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='core.speciality', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['-created'],
            },
        ),
    ]
