# Generated by Django 5.0.6 on 2024-06-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_speciality_funtionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funtionary',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='birthday',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='identification',
            field=models.IntegerField(),
        ),
    ]
