# Generated by Django 5.0.6 on 2024-06-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_funtionary_active_alter_funtionary_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funtionary',
            name='Retus',
            field=models.FileField(default='upload your retus', upload_to='', verbose_name='Retus'),
        ),
        migrations.AddField(
            model_name='funtionary',
            name='contract',
            field=models.FileField(default='upload your contract', upload_to='', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='funtionary',
            name='courses',
            field=models.FileField(default='upload your courses', upload_to='', verbose_name='Cursos'),
        ),
        migrations.AddField(
            model_name='funtionary',
            name='curriculum',
            field=models.FileField(default='upload your cirriculum', upload_to='', verbose_name='Hoja de vida'),
        ),
        migrations.AddField(
            model_name='funtionary',
            name='degree_certificate',
            field=models.FileField(default='upload your degree certificate', upload_to='', verbose_name='Acta de grado'),
        ),
        migrations.AddField(
            model_name='funtionary',
            name='diploma',
            field=models.FileField(default='upload your diploma', upload_to='', verbose_name='Diploma'),
        ),
        migrations.AddField(
            model_name='funtionary',
            name='policy',
            field=models.FileField(default='upload your poliza', max_length=10, upload_to='', verbose_name='Poliza'),
        ),
        migrations.AddField(
            model_name='funtionary',
            name='tariff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='funtionary',
            name='title',
            field=models.FileField(default='upload your title', upload_to='', verbose_name='Convalidacion titulo icfes'),
        ),
        migrations.AddField(
            model_name='funtionary',
            name='type_vinculation',
            field=models.CharField(max_length=10, null=True, verbose_name='Tipo de vinculacion'),
        ),
    ]
