# Generated by Django 5.0.6 on 2024-06-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_funtionary_retus_funtionary_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funtionary',
            name='policy',
            field=models.FileField(default='upload your poliza', upload_to='', verbose_name='Poliza'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='type_vinculation',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo de vinculacion'),
        ),
    ]
