# Generated by Django 5.0.6 on 2024-06-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_funtionary_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funtionary',
            name='Retus',
            field=models.FileField(default='upload your retus', upload_to='retus/', verbose_name='Retus'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='contract',
            field=models.FileField(default='upload your contract', upload_to='contract/', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='courses',
            field=models.FileField(default='upload your courses', upload_to='course/', verbose_name='Cursos'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='curriculum',
            field=models.FileField(default='upload your cirriculum', upload_to='curriculum/', verbose_name='Hoja de vida'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='degree_certificate',
            field=models.FileField(default='upload your degree certificate', upload_to='degree_certificate/', verbose_name='Acta de grado'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='diploma',
            field=models.FileField(default='upload your diploma', upload_to='diploma/', verbose_name='Diploma'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='policy',
            field=models.FileField(default='upload your poliza', upload_to='policy/', verbose_name='Poliza'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='title',
            field=models.FileField(default='upload your title', upload_to='title/', verbose_name='Convalidacion titulo icfes'),
        ),
    ]
