# Generated by Django 5.0.6 on 2024-07-03 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_funtionary_retus_alter_funtionary_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funtionary',
            name='Headquarters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.headquarters', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='Retus',
            field=models.FileField(default='upload your retus', upload_to='Retus/', verbose_name='Retus'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='courses',
            field=models.FileField(default='upload your courses', upload_to='courses/', verbose_name='Cursos'),
        ),
        migrations.AlterField(
            model_name='funtionary',
            name='tariff',
            field=models.IntegerField(null=True, verbose_name='Tarifa'),
        ),
    ]
