# Generated by Django 5.0.6 on 2024-07-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_funtionary_headquarters_alter_funtionary_retus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funtionary',
            name='Headquarters',
        ),
    ]
