# Generated by Django 5.0.6 on 2024-07-10 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_funtionary_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='funtionary',
            name='Headquarters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.headquarters', verbose_name='Sede'),
        ),
    ]
