# Generated by Django 5.0.6 on 2024-07-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_funtionary_headquarters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funtionary',
            name='Headquarters',
        ),
        migrations.AddField(
            model_name='funtionary',
            name='Headquarters',
            field=models.ManyToManyField(null=True, to='core.headquarters', verbose_name='Sede'),
        ),
    ]
