# Generated by Django 5.0.6 on 2024-07-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_funtionary_headquarters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funtionary',
            name='Headquarters',
            field=models.ManyToManyField(to='core.headquarters', verbose_name='Sede'),
        ),
    ]
