# Generated by Django 5.0.6 on 2024-07-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_funtionary_headquarters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funtionary',
            name='Headquarters',
            field=models.ManyToManyField(to='core.headquarters'),
        ),
    ]
